### ISSUE TITLE
[issue] Shortcuts not working

### ISSUE THREAD

**Issue by gerardreches** [TiagoDGomes/iitc-plugin-pogo#3]
**p** and **g** shortcuts to mark portals as pokestops and gyms are not working.

**Comment by TiagoDGomes** [comment]
Try: 

| Browser   | Windows   |  Linux  |  Mac   |   
|---|---|---|---|  
|  Chrome  |   [Alt] + accesskey | [Alt] + accesskey | [Control] [Alt] + accesskey | 
|  Firefox  | [Alt] [Shift] + accesskey | [Alt] [Shift] + accesskey | [Control] [Alt] + accesskey |
|  Opera  |  [Alt] [Shift] + accesskey  |
