### ISSUE TITLE
Suggestion: Load JSON from URL

### ISSUE THREAD

**Issue by pmbarrett314** [TiagoDGomes/iitc-plugin-pogo#7]
I use this collaboratively with some other people in my town, and it would be nice to be able to keep everyone on the same version of our local data. It would be useful to have a setting where we could all just plug in a URL to a file in my github as a setting, push our changes to that and have them automatically show up for everyone else.

**Comment by fortepc** [comment]
How does one merge the changes of multiple people? Does the URL it imports from work the same as pasting the data? I tried to use this to merge two different exports but it didn't work at all. http://tools.knowledgewalls.com/onlinejsonmerger
